export const paths = {
  HOME: "/",
  LOGIN: "/login",
  REGISTER: "register",
  PRODUCTS: "/products",
  PRODUCT_DETAILS: "/product/:id",
  CART: "/cart",
  WISHLIST: "/wishlist",
  ORDERS: "/orders",
  ORDER_DETAILS: "/orders/:orderId",
  CHECKOUT: "/checkout",
  PROFILE: "/profile",
  CHANGE_PASSWORD: "/change-password",
  VERIFY_OTP: "/verify-otp",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/reset-password",

  ADMIN: "/admin",
  ADMIN_USERS: "users",
  ADMIN_CATEGORIES: "/admin/categories",
  ADMIN_ADD_CATEGORY: "/admin/add-category",
  ADMIN_PRODUCTS: "/admin/products",
  ADMIN_ADD_PRODUCT: "/admin/add-product",
  ADMIN_ORDERS: "orders",
  ADMIN_PROFILE: "profile",
};